### ISSUE TITLE
Add install instructions for translatr.py

### ISSUE THREAD

**Issue by resamsel** [resamsel/translatr#19]
Instructions need to be put on a separate page.

# Installation

Install it like Homebrew (http://brew.sh):

`sh < (curl -fsSL https://raw.githubusercontent.com/resamsel/translatr/master/install)`

install file contains:

```
cat > /usr/local/bin/translatr <<EOF
$(contents of translatr.py)
EOF
```

# Usage

First, create a project in the web GUI and copy the project ID (40 character UUID in the URL, i.e. http://localhost:9000/project/6f1ee0a7-b5d1-4c7f-8e4d-46c09fece220 -> project ID: *6f1ee0a7-b5d1-4c7f-8e4d-46c09fece220*).

Then put a .translatr.yml file in any directory that you want to enable pulling/pushing. Translatr will then use that file as configuration.

## Example .translatr.yml for Play messages

```
translatr:
  endpoint: http://localhost:9000
  project_id: 6f1ee0a7-b5d1-4c7f-8e4d-46c09fece220
  pull:
    file_type: play_messages
    target: conf/messages.?{locale.name}
  push:
    file_type: play_messages
    target: conf/messages.?{locale.name}
```

## Pushing

By pushing you send the matching messages files to the given endpoint, creating locales if needed.

`translatr push`

This will overwrite all existing messages, if any. No existing keys/locales will be removed, this is not a sync operation.

## Pulling

By pulling you download all locales into separate files into the configured files (translatr.pull.target key).

`translatr pull`

This will overwrite any existing files locally. All known locales will be downloaded.
